#!/usr/bin/env python3
"""Module to connect to A.R.M to MusicBrainz API"""

import logging
import re
import time
import musicbrainzngs as mb
import werkzeug
from discid import read, Disc

import arm.config.config as cfg
from arm.ripper import utils as u


werkzeug.cached_property = werkzeug.utils.cached_property


def main(disc):
    """
    Depending on the configuration musicbrainz is used
    to identify the music disc. The label of the disc is returned
    or "".
    """
    discid = get_disc_id(disc)
    remember_disc_track_count(disc, discid)
    if cfg.arm_config['GET_AUDIO_TITLE'] == 'musicbrainz':
        return music_brainz(discid, disc)
    return ""


def disc_id_string(discid) -> str:
    """MusicBrainz disc ID from a python-discid object or a raw string."""
    return str(getattr(discid, "id", None) or discid)


def disc_toc_string(discid):
    """TOC string for MusicBrainz fuzzy lookup, or None."""
    toc = getattr(discid, "toc_string", None)
    return str(toc) if toc else None


def remember_disc_track_count(job, discid) -> int:
    """Keep the CD track count even when MusicBrainz does not identify the album."""
    count = 0
    last = getattr(discid, "last_track_num", None)
    try:
        count = int(last or 0)
    except (TypeError, ValueError):
        count = 0
    if not count:
        tracks = getattr(discid, "tracks", None)
        try:
            count = len(list(tracks)) if tracks is not None else 0
        except TypeError:
            count = 0
    if count and not getattr(job, "no_of_titles", None):
        u.database_updater({"no_of_titles": count}, job)
    return count


def get_disc_id(disc):
    """
    Calculates the identifier of the disc

    return:
    identification object from discid package
    """
    return read(disc.devpath)


def music_brainz(discid: str, job) -> str:
    """
    Query MusicBrainz for metadata about an audio disc and update the job with release info.

    This function uses the provided disc ID to fetch metadata from MusicBrainz. If successful,
    it processes the release or CD stub information and updates the job's database records
    with relevant details like artist, album title, and release year.

    Parameters
    ----------
    discid : str
        A disc ID string generated by the `discid` package that uniquely identifies an audio CD.
    job
        A job object that contains metadata and handles logging and database updates.

    Returns
    -------
    str
        The label or title of the disc, or an empty string if the disc could not be processed
        or no information was found.

    Notes
    -----
    - Calls `get_disc_info()` to retrieve disc metadata from MusicBrainz.
    - Uses `check_musicbrainz_data()` to parse and store release data.
    - Returns early with an empty string on error.
    """

    disc_info = get_disc_info(job, discid)
    if disc_info == "":
        logging.info("MusicBrainz did not return a match for this disc")
        return ""

    artist_title = check_musicbrainz_data(job, disc_info)
    if artist_title == "":
        logging.info("MusicBrainz returned data that did not identify this album")
        return ""

    return artist_title


def _mb_retryable(exc) -> bool:
    text = str(exc).lower()
    return isinstance(exc, mb.NetworkError) or "503" in text or "busy" in text or "rate" in text


def _mb_lookup(discid_str, toc=None, cdstubs=True):
    kwargs = {
        "includes": ["artist-credits", "recordings", "release-groups"],
        "cdstubs": cdstubs,
    }
    if toc:
        kwargs["toc"] = toc
    return mb.get_releases_by_discid(discid_str, **kwargs)


def get_disc_info(job, discid: str) -> str:
    """Look up a disc on MusicBrainz, retrying busy errors and falling back to TOC search."""
    mb.set_useragent(app="arm", version=str(job.arm_version), contact="https://github.com/automatic-ripping-machine")
    disc_id_str = disc_id_string(discid)
    toc = disc_toc_string(discid)
    logging.info("MusicBrainz disc id: %s", disc_id_str)
    if toc:
        logging.info("MusicBrainz TOC: %s", toc)
    submit = getattr(discid, "submission_url", None)
    if submit:
        logging.info("MusicBrainz submit URL: %s", submit)

    delays = (1.5, 3.0, 6.0)
    last_exc = None
    for attempt in range(len(delays) + 1):
        try:
            return _mb_lookup(disc_id_str, toc=toc)
        except mb.WebServiceError as exc:
            last_exc = exc
            if _mb_retryable(exc) and attempt < len(delays):
                logging.warning("MusicBrainz busy (attempt %s/%s): %s",
                                attempt + 1, len(delays) + 1, exc)
                time.sleep(delays[attempt])
                continue
            logging.error("MusicBrainz lookup failed: %s", exc)
            break

    if toc:
        try:
            logging.info("Trying MusicBrainz fuzzy TOC search")
            return _mb_lookup("-", toc=toc, cdstubs=False)
        except mb.WebServiceError as exc:
            logging.error("MusicBrainz TOC search failed: %s", exc)
            last_exc = exc
    if last_exc:
        logging.error("Cant reach MB or cd not found ? - ERROR: %s", last_exc)
    return ""


def _medium_track_count(medium) -> int:
    tracks = medium.get("track-list") or []
    if tracks:
        return len(tracks)
    try:
        return int(medium.get("track-count") or 0)
    except (TypeError, ValueError):
        return 0


def _medium_is_cd(medium) -> bool:
    fmt = str(medium.get("format") or "").upper()
    return (not fmt) or ("CD" in fmt)


def _artist_name(release) -> str:
    credit = release.get("artist-credit") or []
    if not credit:
        return ""
    first = credit[0]
    if isinstance(first, str):
        return first
    return (first.get("artist") or {}).get("name") or first.get("name") or ""


def pick_cd_release(release_list, wanted_tracks=None):
    """Pick the best CD-like medium from a MusicBrainz release list."""
    scored = []
    try:
        wanted = int(wanted_tracks) if wanted_tracks else 0
    except (TypeError, ValueError):
        wanted = 0
    for release in release_list or []:
        for medium in release.get("medium-list") or []:
            count = _medium_track_count(medium)
            score = 0
            if _medium_is_cd(medium):
                score += 2
            if wanted and count == wanted:
                score += 5
            elif wanted and count:
                score += max(0, 2 - abs(count - wanted))
            scored.append((score, release, medium))
    if not scored:
        return None, None
    scored.sort(key=lambda item: item[0], reverse=True)
    return scored[0][1], scored[0][2]


def apply_album_release(job, release, medium, disc_info) -> str:
    """Store artist/album/year/tracks from one MusicBrainz release."""
    process_tracks(job, medium.get("track-list") or [])
    new_year = check_date(release)
    title = str(release.get("title") or "no title")
    artist = _artist_name(release) or "Unknown Artist"
    disc = disc_info.get("disc") or {}
    no_of_titles = disc.get("offset-count") or _medium_track_count(medium) or job.no_of_titles
    artist_title = u.clean_for_filename(f"{artist} {title}")
    poster = resolve_cover_url(release.get("id"), release)
    args = {
        "job_id": str(job.job_id),
        "crc_id": release.get("id"),
        "hasnicetitle": True,
        "year": str(new_year),
        "year_auto": str(new_year),
        "title": artist_title,
        "title_auto": artist_title,
        "video_type": "Music",
        "no_of_titles": no_of_titles,
        "poster_url": poster,
        "poster_url_auto": poster,
    }
    logging.info("CD args: %s", args)
    u.database_updater(args, job)
    cover = (release.get("cover-art-archive") or {}).get("artwork")
    logging.info("do have artwork?======%s", cover)
    if get_cd_art(job, disc_info, release=release):
        logging.debug("we got an art image")
    else:
        logging.debug("we didnt get art image")
    return artist_title


def check_musicbrainz_data(job, disc_info: dict) -> str:
    """Process MusicBrainz disc, CD stub, or fuzzy TOC release-list data."""
    if not disc_info:
        return ""

    if "disc" in disc_info:
        logging.info("Processing as a disc")
        release_list = disc_info["disc"].get("release-list", [])
        logging.debug("Number of releases: %s", len(release_list))
        release, medium = pick_cd_release(release_list, job.no_of_titles)
        if release and medium:
            return apply_album_release(job, release, medium, disc_info)
        logging.info("MusicBrainz disc had no usable CD release")
        return ""

    if "cdstub" in disc_info:
        logging.info("Processing as a cdstub")
        process_tracks(job, disc_info["cdstub"].get("track-list") or [], is_stub=True)
        title = str(disc_info["cdstub"].get("title") or "")
        artist = disc_info["cdstub"].get("artist") or ""
        no_of_titles = disc_info["cdstub"].get("track-count")
        artist_title = u.clean_for_filename(f"{artist} {title}")
        args = {
            "job_id": str(job.job_id),
            "crc_id": disc_info["cdstub"].get("id"),
            "hasnicetitle": True,
            "year": "",
            "year_auto": "",
            "title": artist_title,
            "title_auto": artist_title,
            "video_type": "Music",
            "no_of_titles": no_of_titles,
        }
        logging.info("cdstub args: %s", args)
        u.database_updater(args, job)
        logging.info("do have artwork?======No (cdstub)")
        return artist_title

    if "release-list" in disc_info:
        logging.info("Processing MusicBrainz TOC fuzzy match")
        release, medium = pick_cd_release(disc_info.get("release-list"), job.no_of_titles)
        if release and medium:
            return apply_album_release(job, release, medium, disc_info)
        logging.info("MusicBrainz TOC search had no usable CD release")
        return ""

    logging.error("No release information reported by MusicBrainz")
    return ""


def check_date(release: dict) -> str:
    """
    Extract and normalize the release year from a MusicBrainz release dictionary.

    If a 'date' field exists, trims it to just the year.
    If the full date is in the format 'YYYY-MM-DD', only the year ('YYYY') is returned.
    If no date is available, returns an empty string.

    Parameters
    ----------
    release : dict
        A MusicBrainz release dictionary, possibly containing a 'date' field.

    Returns
    -------
    str
        The release year as a string, or an empty string if no date is present.
    """
    # Clean up the date and the title
    if 'date' in release:
        new_year = str(release['date'])
        new_year = re.sub(r"-\d{2}-\d{2}$", "", new_year)
    else:
        # sometimes there is no date in a release
        new_year = ""
    return new_year


def get_title(discid: str, job) -> str:
    """
    Query MusicBrainz for the album title and artist associated with a disc ID.

    This function uses the MusicBrainz API to retrieve the release title and artist name
    for a given disc. If a valid result is found, it updates the job's database entry
    and returns a sanitized string in the format "Artist-Title". If no valid release is
    found, or an error occurs, it updates the database with a failure and returns
    "not identified".

    Parameters
    ----------
    discid : str
        The disc ID obtained from the `discid` package.
    job
        The job object used for accessing the app version and updating the database.

    Returns
    -------
    str
        The sanitized "Artist-Title" string if the disc is identified,
        or "not identified" if no match is found or an error occurs.

    Notes
    -----
    Avoid using logging in this function prior to the `setup_logging()` call,
    as it may interfere with ARM’s logger initialization.
    """

    # Tell musicbrainz what your app is, and how to contact you
    # (this step is required, as per the webservice access rules
    # at http://wiki.musicbrainz.org/XML_Web_Service/Rate_Limiting )
    mb.set_useragent("arm", version=str(job.arm_version), contact="https://github.com/automatic-ripping-machine")
    try:
        disc_info = mb.get_releases_by_discid(discid, includes=['artist-credits'])
        logging.debug(f"disc_info: {disc_info}")
        logging.debug(f"discid = {discid}")
        if 'disc' in disc_info:
            title = str(disc_info['disc']['release-list'][0]['title'])
            # Start setting our db stuff
            artist = str(disc_info['disc']['release-list'][0]['artist-credit'][0]['artist']['name'])
            crc_id = str(disc_info['disc']['release-list'][0]['id'])
        elif 'cdstub' in disc_info:
            title = str(disc_info['cdstub']['title'])
            artist = str(disc_info['cdstub']['artist'])
            # Different id format, but what can you do?
            crc_id = str(disc_info['cdstub']['id'])
        else:
            return "not identified"

        clean_title = u.clean_for_filename(artist) + "-" + u.clean_for_filename(title)
        display_title = u.clean_for_filename(f"{artist} {title}")
        args = {
            'crc_id': crc_id,
            'title': display_title,
            'title_auto': display_title,
            'video_type': "Music"
        }
        u.database_updater(args, job)
        return clean_title
    except (mb.WebServiceError, KeyError):
        return "not identified"


def get_cd_art(job, disc_info: str, release=None) -> bool:
    """Retrieve and store CD artwork from MusicBrainz if available."""
    try:
        if release is not None:
            release_list = [release]
        elif disc_info and "disc" in disc_info:
            release_list = disc_info["disc"].get("release-list") or []
        elif disc_info and "release-list" in disc_info:
            release_list = disc_info.get("release-list") or []
        else:
            return False
        logging.debug("release_list: %s", release_list)
        first_release_with_artwork = next(
            (
                item for item in release_list
                if item.get("id") and item.get("cover-art-archive", {}).get("artwork") != "false"
            ),
            None,
        )
        chosen = first_release_with_artwork or (release if release and release.get("id") else None)
        if chosen is None and release_list:
            chosen = next((item for item in release_list if item.get("id")), None)
        if chosen is None:
            return False
        poster = resolve_cover_url(chosen.get("id"), chosen)
        if not poster:
            return False
        u.database_updater({"poster_url": poster, "poster_url_auto": poster}, job)
        logging.debug("poster_url: %s", poster)
        return True
    except mb.WebServiceError as exc:
        logging.error("get_cd_art ERROR: %s", exc)
        return False


def process_tracks(job, mb_track_list: dict, is_stub=False):
    """Store MusicBrainz tracks; missing length/title must not abort identification."""
    for idx, track in enumerate(mb_track_list or []):
        track_leng = 0
        rec = track.get("recording") or {}
        try:
            if is_stub:
                track_leng = int(track.get("length") or 0)
            else:
                track_leng = int(rec.get("length") or track.get("length") or 0)
        except (TypeError, ValueError, KeyError):
            logging.error("Failed to find track length")
            track_leng = 0
        trackno = track.get("number", idx + 1)
        if is_stub:
            title = track.get("title") or f"Untitled track {trackno}"
        else:
            title = rec.get("title") or track.get("title") or f"Untitled track {trackno}"
        u.put_track(job, trackno, track_leng, "n/a", 0.1, False, "ABCDE", title)


_RELEASE_MBID = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)
_PLACEHOLDER_TITLES = frozenset({"", "not identified", "none", "null", "title unknown"})


def is_release_mbid(value):
    """True when value looks like a MusicBrainz release UUID."""
    return bool(value and _RELEASE_MBID.match(str(value)))


def cover_url_for_release(mbid):
    """Cover Art Archive front image for a MusicBrainz release."""
    if not is_release_mbid(mbid):
        return None
    return f"https://coverartarchive.org/release/{mbid}/front-500"


def cover_url_for_release_group(mbid):
    """Cover Art Archive front image for a MusicBrainz release group."""
    if not is_release_mbid(mbid):
        return None
    return f"https://coverartarchive.org/release-group/{mbid}/front-500"


def _release_group_id(release):
    group = (release or {}).get("release-group")
    if isinstance(group, dict):
        return group.get("id")
    return None


def _first_cover_url(artlist):
    images = (artlist or {}).get("images") or []
    chosen = next((image for image in images if image.get("front")), None) or (images[0] if images else None)
    if not chosen:
        return None
    thumbs = chosen.get("thumbnails") or {}
    return thumbs.get("500") or thumbs.get("large") or thumbs.get("small") or chosen.get("image")


def resolve_cover_url(mbid, release=None):
    """Working cover URL: this edition if CAA has it, otherwise the release group."""
    try:
        if is_release_mbid(mbid):
            url = _first_cover_url(mb.get_image_list(mbid))
            if url:
                return url
    except mb.WebServiceError as exc:
        logging.debug("CAA release images failed for %s: %s", mbid, exc)
    rgid = _release_group_id(release)
    try:
        if is_release_mbid(rgid) and hasattr(mb, "get_release_group_image_list"):
            url = _first_cover_url(mb.get_release_group_image_list(rgid))
            if url:
                return url
    except mb.WebServiceError as exc:
        logging.debug("CAA release-group images failed for %s: %s", rgid, exc)
    return cover_url_for_release_group(rgid) or cover_url_for_release(mbid)


def _mb_useragent(arm_version="unknown"):
    mb.set_useragent(
        "arm",
        version=str(arm_version or "unknown"),
        contact="https://github.com/automatic-ripping-machine",
    )


def search_releases_for_ui(query, year="", arm_version="unknown"):
    """Search MusicBrainz releases for the Title Search page.

    Returns the same OMDb-shaped dict list_titles.html already renders, with
    the release MBID in imdbID so gettitle/updatetitle can reuse those URLs.
    """
    title = " ".join(str(query or "").split())
    if title.lower() in _PLACEHOLDER_TITLES:
        return {"Search": []}
    year = str(year or "").strip()
    lucene = title
    if year.isdigit():
        lucene = f"{title} AND date:{year}"
    try:
        _mb_useragent(arm_version)
        info = mb.search_releases(query=lucene, limit=20)
    except mb.WebServiceError:
        logging.debug("MusicBrainz release search failed for %s", lucene, exc_info=True)
        return {"Search": [], "Error": "MusicBrainz search failed"}
    results = []
    for release in info.get("release-list") or []:
        mbid = release.get("id") or ""
        if not is_release_mbid(mbid):
            continue
        artist = _artist_name(release)
        album = release.get("title") or ""
        date = str(release.get("date") or "")
        display = f"{artist} {album}".strip() if artist else album
        results.append({
            "Title": display,
            "Year": date[:4] if date else "",
            "imdbID": mbid,
            "Type": "Music",
            "Poster": f"https://coverartarchive.org/release/{mbid}/front-250",
        })
    return {"Search": results}


def release_card_for_ui(mbid, arm_version="unknown"):
    """OMDb-shaped dict for the Title Search confirmation page."""
    details = release_details_for_ui(mbid, arm_version)
    if not details:
        return None
    poster = f"https://coverartarchive.org/release/{mbid}/front-500"
    try:
        _mb_useragent(arm_version)
        poster = resolve_cover_url(mbid) or poster
    except mb.WebServiceError:
        logging.debug("Cover art lookup failed for %s", mbid, exc_info=True)
    artist = details.get("artist") or ""
    album = details.get("album") or ""
    title = f"{artist} {album}".strip() if artist else album
    bits = [details.get("primary_type") or "Album"]
    if details.get("label"):
        bits.append(details["label"])
    if details.get("country"):
        bits.append(details["country"])
    return {
        "Title": title,
        "Year": details.get("year") or "",
        "imdbID": mbid,
        "Type": "Music",
        "Poster": poster,
        "Plot": " · ".join(bits),
    }


def release_details_for_ui(mbid, arm_version="unknown"):
    """Look up a MusicBrainz release for the job-detail page.

    For audio CDs, job.crc_id is a MusicBrainz release UUID, not a DVD CRC64.
    CD stubs never get a UUID, so this returns None and the page falls back to
    whatever ARM already stored on the job. Barcode and catalog number come from
    the release, not OMDb/IMDb.
    """
    if not is_release_mbid(mbid):
        return None
    try:
        _mb_useragent(arm_version)
        info = mb.get_release_by_id(
            mbid, includes=["artists", "labels", "release-groups"]
        )
    except mb.WebServiceError:
        logging.debug("MusicBrainz release lookup failed for %s", mbid, exc_info=True)
        return None
    release = info.get("release") or {}
    artist = ""
    credit = release.get("artist-credit") or []
    if credit:
        artist = (credit[0].get("artist") or {}).get("name") or credit[0].get("name") or ""
    labels = []
    catalogs = []
    for item in release.get("label-info-list") or []:
        name = (item.get("label") or {}).get("name")
        if name and name not in labels:
            labels.append(name)
        catalog = (item.get("catalog-number") or "").strip()
        if catalog and catalog not in catalogs:
            catalogs.append(catalog)
    release_group = release.get("release-group") or {}
    date = str(release.get("date") or "")
    barcode = str(release.get("barcode") or "").strip()
    return {
        "artist": artist,
        "album": release.get("title") or "",
        "year": date[:4] if date else "",
        "label": ", ".join(labels),
        "barcode": barcode,
        "catalog": ", ".join(catalogs),
        "country": release.get("country") or "",
        "status": release.get("status") or "",
        "primary_type": release_group.get("primary-type") or "",
        "mbid": mbid,
        "url": f"https://musicbrainz.org/release/{mbid}",
    }


if __name__ == "__main__":
    # this will break our logging if it ever triggers for arm
    disc = Disc("/dev/cdrom")
    myid = get_disc_id(disc)
    logging.debug("DiscID: %s (%s)", str(myid), myid.freedb_id)
    logging.debug("URL: %s", myid.submission_url)
    logging.debug("Tracks: %s", myid.tracks)
    logging.debug("Musicbrain: %s", music_brainz(myid, None))
